### ISSUE TITLE
Install Photoshop 

### ISSUE THREAD

**Issue by achintagrawal** [opencodeiiita/LetsDesign#1]
Make a simple hello opencode poster. Comment the snapshot and there is a task 1 folder, you have to add that screenshot in that folder and make a PR.
Download it from:  https://prodesigntools.com/prdl-download/Photoshop/66A1D1E00DE44601B041A631261EC584/1507846032938/AdobePhotoshop19-mul_x64.zip

**Comment by pra1hamesh** [comment]
### an amazing start for desing with **Hello Opencode** Poster is Here.
![Screenshot (37)](https://user-images.githubusercontent.com/58396450/72927335-022d8c80-3d7c-11ea-852b-3b8df7aefb56.png)

**Comment by aarpit1010** [comment]
![Screenshot (24)](https://user-images.githubusercontent.com/58038078/72927663-b16a6380-3d7c-11ea-8b69-45235b085696.png)

**Comment by achintagrawal** [comment]
@Lulz5ec @aarpit1010 there is a task 1 folder. you have to add that screenshot in that folder and make a PR.

**Comment by garvitchittora** [comment]
![Screenshot (33)](https://user-images.githubusercontent.com/54021348/72969753-2cb72e00-3dec-11ea-83bb-8f8495f405a0.png)
TASK 1 DONE .

**Comment by Mridul20** [comment]
screenshot added

**Comment by Mridul20** [comment]
![Mridul20](https://user-images.githubusercontent.com/53915334/72970228-2b3a3580-3ded-11ea-803e-d08d9e644c4a.png)

**Comment by pradhuman1** [comment]
Can we do it in any app other than photoshop

**Comment by kumarmanish03** [comment]
![manish-kumar-2000](https://user-images.githubusercontent.com/41566808/73598066-796fd700-4559-11ea-8790-419226696138.png)

ss

**Comment by sarthakm21** [comment]
![sarthakm21](https://user-images.githubusercontent.com/58396189/73682902-48bda800-46e7-11ea-8be5-9d8270aaad94.PNG)
