### ISSUE TITLE
Adobe illustrator

### ISSUE THREAD

**Issue by achintagrawal** [opencodeiiita/LetsDesign#30]
Download the software from the given link and install it. Add the screenshot in the comment section and also in the task6 folder. 

download link:
https://prodesigntools.com/prdl-download/Illustrator/C1208DBFE1D04A81A21C62CDF6A96AC6/1509968804429/AdobeIllustrator22_HD_win64.zip

**Comment by prince-7** [comment]
![ILLUSTRATOR](https://user-images.githubusercontent.com/53997924/73131156-d5070580-402b-11ea-8b65-67c8bf17a8df.PNG)

**Comment by shivi2408** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/55327107/73135430-c6d6da80-4067-11ea-86d1-31d5e873ceeb.png)
screenshot added

**Comment by sarthakm21** [comment]
![sarthakm21](https://user-images.githubusercontent.com/58396189/73138831-44f9a800-408d-11ea-8c42-f71a2e2ee987.PNG)

**Comment by Cybertron-Avneesh** [comment]
![adobe illustrator](https://user-images.githubusercontent.com/54072374/73464428-be1a2900-4333-11ea-8755-b8a72325425e.png)
