### ISSUE TITLE
Play with words 2 

### ISSUE THREAD

**Issue by achintagrawal** [opencodeiiita/LetsDesign#45]
Make a minimal typo on one of the words given below:
1) friendship
2) politics
3) food
4) dream
Export them in jpeg form and store them in the task7 folder. Also, add a screenshot in the comment section.

**Comment by sggts04** [comment]
![image](https://user-images.githubusercontent.com/20678047/73259865-b604a100-41ee-11ea-9320-9ba949e64dfe.png)
