### ISSUE TITLE
Company App logo

### ISSUE THREAD

**Issue by achintagrawal** [opencodeiiita/LetsDesign#46]
You have to make a logo for a travel and tour company app whose main motto is to create a custom tour app to provide higher user experience and satisfaction providing more flexibility in planning the tour.

Export them in jpeg form and store them in the task8 folder. Also, add a screenshot in the comment section.
check this logo for idea:
![fromto0](https://user-images.githubusercontent.com/42510489/73198521-2234c580-4159-11ea-97b3-6f25996cb964.jpg)

**Comment by blaze-assault** [comment]
https://github.com/opencodeiiita/LetsDesign/pull/70

@achintagrawal  please review it
