### ISSUE TITLE
Apk Comedian poster 

### ISSUE THREAD

**Issue by achintagrawal** [opencodeiiita/LetsDesign#49]
As we all know Aparoksha is coming, it has a comedy night for you people. make a poster of a comedy night featuring your favorite comedian whom you want to see in this year Aparoksha with all the details mentioned in the poster like date, venue, time etc. 

Export it in jpeg form and store them in the task9 folder. Also, add a screenshot in the comment section

**Comment by sggts04** [comment]
![image](https://user-images.githubusercontent.com/20678047/73258305-6c668700-41eb-11ea-84f0-9c509befcb2b.png)

**Comment by sarthakm21** [comment]
![stc](https://user-images.githubusercontent.com/58396189/73725860-52c9c000-4754-11ea-8262-b1133cf1315c.PNG)
